### ISSUE TITLE
Parser chokes on quotation marks in --data argument

### ISSUE THREAD

**Issue by rodw** [NickCarneiro/curlconverter#12]
(I'm basing this report on the behavior of the online demonstration at http://curl.trillworks.com/.  My apologies if that demo is simply out of date and this problem is already fixed in the most recent code, or if this issue is an artifact of the web interface.)

It seems that I cannot pass single or double quote characters in the curl command.

For example, given:

```bash
curl -X POST http://example.com/ --data "foo=bar"
```
curlconverter generates the proper body content (taking the Node.js output):

```js
var dataString = 'foo=bar';
```

The same is true for the single quote version:

```bash
curl -X POST http://example.com/ --data 'foo=bar'
```

However, if I try to add quotation marks in the body content, e.g.:

```bash
curl -X POST http://example.com/ --data 'foo="bar"'
```

The output body is truncated at the first quotation mark:

```js
var dataString = 'foo=';
```

There are similar problems for all of the variations of this input I could think of, for example:

```bash
curl -X POST http://example.com/ --data "foo=\"bar\""
curl -X POST http://example.com/ --data 'foo=\"bar\"'
curl -X POST http://example.com/ --data "foo=\'bar\'"
curl -X POST http://example.com/ --data "foo='bar'"
```
etc.

**Comment by rodw** [comment]
Actually, it looks like this problem _has_ been fixed in the latest version of the code, via this commit - https://github.com/NickCarneiro/curlconverter/commit/d4da3faa0b81d5448edfcaaf12f80aab9b4cef16

I guess you can read this bug as reporting that http://curl.trillworks.com/ has not been updated yet.

**Comment by NickCarneiro** [comment]
This bug still affects the `--data` param. I'll add your test cases this weekend and update the parser.
